// app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/sharedcomponents/Header";
import Footer from "@/components/sharedcomponents/Footer";
import { AuthProvider } from "../lib/context/auth";
import AuthCheck from "@/components/sharedcomponents/Authcheck";
import Navigation from "@/components/sharedcomponents/Navigation";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

// Font files can be colocated inside of `pages`
const myFont = localFont({
  src: "./Clash.woff2",
  display: "swap",
  variable: "--font-clash",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${myFont.variable} `}>
      <body className={`${inter.className} `}>
        <AuthProvider>
          <Header />
          <div className="grid grid-cols-5 grid-flow-col bg-[#E9EBFD] h-full gap-2 pt-4">
            <AuthCheck>
              <div className="hidden md:block md:col-span-1 bg-[#E9EBFD]">
                <div className="hidden md:block">
                  <Navigation />
                </div>
              </div>
            </AuthCheck>
            <div className="col-span-5 md:col-span-5 bg-[#E9EBFD] h-full overflow-scroll">
              {children}
            </div>
          </div>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
