// app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/sharedcomponents/Header";
import Footer from "@/components/sharedcomponents/Footer";
import { AuthProvider } from "../lib/context/auth";
import AuthCheck from "@/components/sharedcomponents/Authcheck";
import {
  Home,
  MessageSquareIcon,
  Badge,
  FileIcon,
  SearchIcon,
  UserIcon,
} from "lucide-react";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Header />
          <div className="h-full">
            <div className="grid grid-cols-5 grid-flow-col gap-2 pt-4">
              <AuthCheck redirect={false}>
                <div className="hidden md:block">
                  <nav className="grid items-start px-2 text-sm font-medium lg:px-4">
                    {/* <a
                      href="#"
                      className="flex items-center gap-3 rounded-lg px-4 py-3 text-muted-foreground transition-all hover:text-primary"
                    >
                      <Home className="h-4 w-4" />
                      Dashboard
                    </a>
                    <a
                      href="#"
                      className="flex items-center gap-3 rounded-lg px-4 py-3 text-muted-foreground transition-all hover:text-primary"
                    >
                      <MessageSquareIcon className="h-4 w-4" />
                      Messages
                      <Badge className="ml-auto flex h-6 w-6 shrink-0 items-center justify-center rounded-full">
                        6
                      </Badge>
                    </a>
                    <a
                      href="#"
                      className="flex items-center gap-3 rounded-lg bg-[#CCCCF5] px-4 py-3 text-primary transition-all hover:text-primary"
                    >
                      <FileIcon className="h-4 w-4" />
                      Applications
                    </a> */}
                    <Link
                      href="/jobs"
                      className="inline-flex items-center space-x-2"
                    >
                      <SearchIcon className="h-4 w-4" />
                      <span>Find Jobs</span>
                    </Link>

                    {/* <a
                      href="#"
                      className="flex items-center gap-3 rounded-lg px-4 py-3 text-muted-foreground transition-all hover:text-primary"
                    >
                      <SearchIcon className="h-4 w-4" />
                      Browse Companies
                    </a>
                    <a
                      href="#"
                      className="flex items-center gap-3 border-b rounded-lg px-4 py-3 text-muted-foreground transition-all hover:text-primary"
                    >
                      <UserIcon className="h-4 w-4" />
                      My Profile
                    </a>
                    <div className="px-4 py-3 text-muted-foreground transition-all hover:text-primary">
                      <p className="text-xl">Settings</p>
                    </div>
                    <a
                      href="#"
                      className="flex items-center gap-3 rounded-lg px-4 py-3 text-muted-foreground transition-all hover:text-primary"
                    >
                      <UserIcon className="h-4 w-4" />
                      My Profile
                    </a> */}
                  </nav>
                </div>
              </AuthCheck>
              {children}
            </div>
          </div>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
